# Generated by Django 6.0.6 on 2026-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_employee_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
