# Generated by Django 6.0.6 on 2026-06-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_recognitionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="recognitionlog",
            name="camera_name",
            field=models.CharField(default="Unknown Camera", max_length=100),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="camera_name",
            field=models.CharField(default="Unknown Camera", max_length=100),
        ),
    ]
