# Generated by Django 5.2.15 on 2026-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_cameralog_id_alter_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
