# Generated by Django 5.2.15 on 2026-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_employee_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitorlogo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(default="Unknown Visitor", max_length=100),
                ),
                ("Snapshot", models.ImageField(upload_to="visitors/")),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
