# Generated by Django 5.2.15 on 2026-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("time_in", models.TimeField(auto_now_add=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(default="Present", max_length=20)),
            ],
        ),
    ]
