# Generated by Django 5.2.15 on 2026-06-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time_in",
            new_name="entery_time",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="time_out",
            new_name="exit_time",
        ),
    ]
