# Generated by Django 5.2.15 on 2026-06-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_rename_time_in_attendance_entery_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="entery_time",
            new_name="entry_time",
        ),
    ]
