# Generated by Django 5.2.15 on 2026-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryExitLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(default="Unknown Person", max_length=100),
                ),
                ("event", models.CharField(default="Unknown Camera", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
