# Generated by Django 5.2.15 on 2026-06-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_entryexitlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("entry_count", models.IntegerField(default=0)),
                ("exit_count", models.IntegerField(default=0)),
                ("occupancy", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="EntryExitLog",
        ),
    ]
