# Generated by Django 5.2.15 on 2026-06-22 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_visitoranalytics_delete_entryexitlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="entry_time",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="exit_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="first_entry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="last_exit",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
