# Generated by Django 5.2.15 on 2026-06-22 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_remove_attendance_entry_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="first_entry",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="last_exit",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="attendance",
            name="entry_time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="exit_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
