# Generated by Django 5.2.15 on 2026-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_remove_attendance_first_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="blacklist/")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
