# Generated by Django 5.2.15 on 2026-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_blacklistperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorlogo",
            name="camera_name",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
