# Generated by Django 5.2.15 on 2026-06-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_visitorlogo_camera_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_url', models.CharField(blank=True, max_length=255)),
                ('camera_type', models.CharField(choices=[('RTSP', 'RTSP'), ('IP', 'IP'), ('USB', 'USB'), ('Webcam', 'Webcam')], default='Webcam', max_length=20)),
                ('group', models.CharField(default='Default', max_length=100)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Warning', 'Warning'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Healthy', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('recording_status', models.CharField(choices=[('Recording', 'Recording'), ('Not Recording', 'Not Recording'), ('Paused', 'Paused')], default='Not Recording', max_length=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('floor_mapping', models.CharField(blank=True, max_length=150)),
                ('live_fps', models.FloatField(default=0)),
                ('bitrate_kbps', models.PositiveIntegerField(default=0)),
                ('stream_quality', models.CharField(choices=[('Auto', 'Auto'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('HD', 'HD')], default='Auto', max_length=20)),
                ('audio_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
