# Generated by Django 5.2.15 on 2026-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_no',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
