# Generated by Django 5.2.15 on 2026-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_camera_camera_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='employees/front/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='employees/left/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='employees/right/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
