# Generated by Django 5.2.15 on 2026-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='employees/extra/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('RTSP', 'RTSP'), ('IP', 'IP'), ('USB', 'USB'), ('Webcam', 'Webcam'), ('IP Camera', 'IP Camera'), ('PTZ Camera', 'PTZ Camera'), ('Dome Camera', 'Dome Camera'), ('Bullet Camera', 'Bullet Camera')], default='Webcam', max_length=20),
        ),
    ]
