# Generated by Django 5.2.15 on 2026-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
